In [3]:
import pandas as pd
import numpy as np
import seaborn as sns; sns.set('talk')
import matplotlib.pyplot as plt
params = {'legend.fontsize': 'large',
          'figure.figsize': (16, 9),
         'axes.labelsize': 'medium',
         'axes.titlesize':'x-large',
         'xtick.labelsize':'small',
         'ytick.labelsize':'small'}
plt.rcParams.update(params)

In [4]:
models = ['resnet', 'densenet', 'b-resnet', 'b-densenet', 'msdnet']

In [6]:
pc_runs = {
    'b-resnet': pd.read_csv('resnet_localhost.csv', index_col=0)
}

In [91]:
cols = pc_runs['b-resnet'].columns.tolist()
cols

['exit', 'prediction', 'confidence', 'target', 'time', 'correct', 'sample']

In [12]:
for data in pc_runs['b-resnet'].groupby(['sample', 'exit']):
    data[1]


((0, 0),    exit  prediction  confidence  target      time  correct  sample
0     0          36    0.277228       0  2548.079    False       0)


In [106]:
best_prediction = []
df = pd.DataFrame()
for data in pc_runs['b-resnet'].groupby(['sample']):
    tmp = data[1][np.argmax(np.array(data[1].confidence)):np.argmax(np.array(data[1].confidence))+1].values.tolist()
    df = df.append(dict(zip(cols,tmp[0])), ignore_index=True)

In [142]:
best_prediction = []
df = pd.DataFrame()
for data in pc_runs['b-resnet'].groupby(['sample']):
    d = data[1].loc[data[1]['time']<30]
    if not d.empty:
        
        tmp = d[np.argmax(np.array(d.confidence)):np.argmax(np.array(d.confidence))+1].values.tolist()
        df = df.append(dict(zip(cols,tmp[0])), ignore_index=True)

In [62]:
best_prediction

[array([[3, 0, 0.9991180300712584, 0, 2588.9880000000007, True, 0]],
       dtype=object),
 array([[3, 0, 0.9999985694885254, 0, 48.153400000000346, True, 1]],
       dtype=object),
 array([[3, 0, 0.9999501705169678, 0, 46.35310000000104, True, 2]],
       dtype=object),
 array([[3, 0, 0.9999982118606568, 0, 47.477199999999435, True, 3]],
       dtype=object),
 array([[3, 0, 0.999992609024048, 0, 49.233499999999715, True, 4]],
       dtype=object),
 array([[3, 0, 0.9997722506523132, 0, 48.48609999999986, True, 5]],
       dtype=object),
 array([[3, 0, 0.9999986886978148, 0, 47.35129999999898, True, 6]],
       dtype=object),
 array([[3, 0, 1.0, 0, 48.876599999999826, True, 7]], dtype=object),
 array([[3, 0, 0.999998927116394, 0, 47.16379999999987, True, 8]],
       dtype=object),
 array([[2, 92, 0.7552735209465027, 0, 41.4197999999999, False, 9]],
       dtype=object),
 array([[2, 0, 0.9999992847442628, 0, 44.29879999999997, True, 10]],
       dtype=object),
 array([[3, 0, 0.9999985694

In [143]:
df.mean()

confidence       0.695728
correct          0.653923
exit             0.856886
prediction      47.929744
sample        2499.685749
target          49.503603
time            16.956304
dtype: float64

In [120]:
grouped = pc_runs['b-resnet'].groupby(['sample', 'exit']).first()
grouped.loc[grouped['time'] < 40]

prediction  confidence  target     time  correct
sample exit                                                  
1      0              0    0.897793       0  12.6200     True
       1              0    0.546599       0  18.3305     True
2      0              0    0.336024       0  11.1910     True
       1              0    0.635181       0  16.5254     True
3      0             59    0.575749       0  12.3860    False
       1              0    0.996281       0  17.6345     True
4      0              0    0.488617       0  14.2152     True
       1              0    0.949574       0  19.4435     True
5      0              0    0.908752       0  13.4500     True
       1              0    0.999028       0  18.6943     True
6      0              0    0.998353       0  11.8473     True
       1              0    0.999984       0  17.1983     True
7      0              0    0.782887       0  13.7432     True
       1              0    0.998699       0  19.1058     True
8      0             70    0.414429       0  11.9440    False
       1              0    0.992649       0  17.4642     True
9      0             92    0.300172       0  10.4561    False
       1             36    0.460147       0  15.8558    False
10     0              0    0.998722       0  12.9172     True
       1              0    0.999983       0  18.2112     True
11     0              0    0.324639       0  12.1270     True
       1              0    0.938399       0  17.4209     True
12     0              0    0.999652       0  11.2358     True
       1              0    0.998800       0  16.6602     True
13     0             36    0.584343       0  11.8952    False
       1              0    0.996007       0  17.9500     True
14     0              0    0.106435       0  11.5089     True
       1              0    0.953860       0  17.0798     True
15     0              0    0.494133       0  12.8223     True
       1              0    0.987697       0  18.2265     True
...                 ...         ...     ...      ...      ...
4985   0             25    0.124015      99  11.5697    False
       1             17    0.093396      99  16.8400    False
4986   0             72    0.089768      99  11.8660    False
       1              2    0.278800      99  17.1124    False
4987   0             98    0.131309      99  10.8864    False
       1             69    0.587116      99  16.1364    False
4988   0             46    0.555180      99  16.3721    False
       1             46    0.307839      99  21.6025    False
4989   0             48    0.385795      99  11.8078    False
       1             48    0.880810      99  17.0708    False
4990   0             63    0.391204      99  11.5240    False
       1             99    0.204126      99  17.0988     True
4991   0              8    0.312495      99  15.7815    False
       1              8    0.192433      99  21.2247    False
4992   0              3    0.134340      99  10.2329    False
       1             48    0.180141      99  15.7094    False
4993   0             72    0.160027      99  11.4411    False
       1             94    0.142701      99  16.7692    False
4994   0              9    0.188059      99  14.5838    False
       1             94    0.659047      99  20.1989    False
4995   0             25    0.122230      99  11.4842    False
       1             43    0.293732      99  16.9195    False
4996   0             63    0.161115      99  10.5295    False
       1             99    0.267338      99  16.0116     True
4997   0             46    0.302566      99  10.9390    False
       1             46    0.460433      99  16.9411    False
4998   0             54    0.258699      99  10.1536    False
       1             99    0.265294      99  15.7780     True
4999   0             45    0.243096      99  10.6998    False
       1             72    0.425324      99  15.9871    False

[9997 rows x 5 columns]

In [121]:
grouped.exit

AttributeError: 'DataFrame' object has no attribute 'exit'